// 1. Import Node.js's built-in File System module
//const fs = require('fs');

//console.log("Initializing backend file creator...");

// 2. The text content we want to save
//const secretMessage = "This text file was generated by my Node.js server script!";

// 3. FIX: Make sure this says 'fs.writeFile' (NOT fs.write)
//fs.writeFile('log.txt', secretMessage, (error) => {
  //  if (error) {
    //    console.log("Something went wrong:", error);
    //} else {
      //  console.log("🎉 Success! Look inside your folder for a new file named 'log.txt'.");
    //}
//});
// 1. Import Node's built-in HTTP networking module

//const http = require('http');

// 2. Define the network port address (3000 is standard for testing)
//const PORT = 3000;

// 3. Create the server engine
//const server = http.createServer((request, response) => {
  //  console.log("📩 Incoming request received from a web browser!");

    // Set the response headers to send back plain text
    //response.writeHead(200, { 'Content-Type': 'text/plain' });
    
    // Send a message back to the web browser screen
    //response.end("Hello from your custom Node.js Backend Server!");
//});

// 4. Start listening for visitors on Port 3000
//server.listen(PORT, () => {
  //  console.log(`🌐 Server is live and running at http://localhost:${PORT}/`);
    //console.log("Press Ctrl + C in the terminal to turn off the server.");
//});

//const http = require('http');
//const PORT = 3000;

// This mimics a real full-stack user database
//const userData = {
 //   message: "Hello from your custom Node.js Backend Server!",
   // serverStatus: "Online",
    //developer: "Alex",
    //totalClicksRecorded: 150
//};

//const server = http.createServer((request, response) => {
    // Enable CORS so our frontend index.html file is allowed to talk to this server
  //  response.setHeader('Access-Control-Allow-Origin', '*');
    
    // Tell the browser we are sending professional JSON data back
    //response.writeHead(200, { 'Content-Type': 'application/json' });
    
    // Convert our data object into a clean network string and send it
    //response.end(JSON.stringify(userData));
//});

//server.listen(PORT, () => {
  //  console.log(`🚀 API Server running at http://localhost:${PORT}/`);
//});
// ==========================================
// 5. FETCHING DATA FROM OUR BACKEND SERVER
// ==========================================
//function getBackendData() {
    // Fetch data over the local network from port 3000
  //  fetch('http://localhost:3000/')
    //    .then(response => response.json()) // Convert incoming network text to a JS object
      //  .then(data => {
        //    console.log("Data received from backend:", data);
            
            // Target the main HTML title and change it to the backend message!
          //  const title = document.querySelector("#main-title");
            //title.textContent = data.message;
        //})
        //.catch(error => {
          //  console.log("Could not connect to backend server:", error);
        //});
//}

// Automatically trigger the fetch operation as soon as the window finishes loading
//window.addEventListener("load", getBackendData);
// 1. Import the Express framework
const express = require('express');
const cors = require('cors');
const fs = require('fs'); // Import File System to read/write to database.json

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json()); // Crucial: Allows Express to read incoming JSON data from the frontend

// Add this so the main page displays a friendly message instead of an error
app.get('/', (req, res) => {
    res.send("Welcome to my Database Server! Go to /api/users to see the data.");
});

// 1. GET ROUTE: Read and send users from our database file
app.get('/api/users', (req, res) => {
    fs.readFile('database.json', 'utf8', (err, data) => {
        if (err) {
            return res.status(500).json({ error: "Failed to read database" });
        }
        // Send the parsed JSON data back to the browser
        res.json(JSON.parse(data));
    });
});

// 2. POST ROUTE: Receive a new user from the frontend and save it permanently
app.post('/api/users', (req, res) => {
    const newUser = req.body; // Capture the incoming user data object

    // Read the current file contents first
    fs.readFile('database.json', 'utf8', (err, data) => {
        if (err) return res.status(500).json({ error: "Database error" });

        const currentUsers = JSON.parse(data); // Turn file text into a JS array
        currentUsers.push(newUser); // Add our new user to the list

        // Write the updated array back onto the hard drive text file
        fs.writeFile('database.json', JSON.stringify(currentUsers, null, 2), (err) => {
            if (err) return res.status(500).json({ error: "Failed to save data" });
            res.json({ message: "🎉 User added successfully!", database: currentUsers });
        });
    });
});

app.listen(PORT, () => {
    console.log(`🚀 Database API Server running at http://localhost:${PORT}/api/users`);
});
